import { existsSync } from 'node:fs';
import { readFile, readdir } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import { z } from 'zod';
import {
  EdgeSchema,
  createLab,
  parseArtifactMarkdown,
  rebuildLabIndex,
  renderLabIndex,
  resolveLabDir,
  validateLabLayout,
} from '../lab';
import { INDEX_AUTOGENERATED_HEADER } from '../lab/indexer';
import { logger } from '../utils';

export interface DoctorOptions {
  cwd?: string;
  labDir?: string;
  json?: boolean;
  repair?: boolean;
}

export type DoctorStatus = 'ok' | 'warn' | 'error';

export interface DoctorCheck {
  status: DoctorStatus;
  label: string;
  message: string;
}

export interface DoctorResult {
  ok: boolean;
  exitCode: 0 | 1 | 2;
  labDir: string;
  repaired: boolean;
  checks: DoctorCheck[];
}

interface DraftRecord {
  file: string;
  nodeId: string;
}

function formatZodError(error: z.ZodError): string {
  return error.issues
    .map((issue) => {
      const path = issue.path.length > 0 ? `${issue.path.join('.')}: ` : '';
      return `${path}${issue.message}`;
    })
    .join('; ');
}

function pushCheck(
  checks: DoctorCheck[],
  status: DoctorStatus,
  label: string,
  message: string,
): void {
  checks.push({ status, label, message });
}

function expectedDraftFilename(nodeId: string): string {
  return `${nodeId.replace(':', '-')}.md`;
}

function normalizeGeneratedIndex(content: string): string {
  return content
    .replace(/^Generated: .+$/m, 'Generated: <ignored>')
    .replace(/^- Last validation: .+$/m, '- Last validation: <ignored>');
}

async function validateDrafts(
  labDir: string,
  checks: DoctorCheck[],
): Promise<DraftRecord[]> {
  const draftsDir = resolve(labDir, 'drafts');

  if (!existsSync(draftsDir)) {
    return [];
  }

  const files = (await readdir(draftsDir)).filter((file) =>
    file.endsWith('.md'),
  );
  const records: DraftRecord[] = [];
  const seenNodeIds = new Map<string, string>();

  if (files.length === 0) {
    pushCheck(checks, 'ok', 'drafts', 'No draft artifacts yet.');
    return records;
  }

  for (const file of files.sort()) {
    const path = resolve(draftsDir, file);

    try {
      const markdown = await readFile(path, 'utf8');
      const { frontmatter } = parseArtifactMarkdown(markdown);
      const expectedFile = expectedDraftFilename(frontmatter.node_id);

      records.push({ file, nodeId: frontmatter.node_id });

      if (frontmatter.type !== frontmatter.node_id.split(':', 1)[0]) {
        pushCheck(
          checks,
          'error',
          `drafts/${file}`,
          `type "${frontmatter.type}" does not match node_id "${frontmatter.node_id}".`,
        );
      }

      if (file !== expectedFile) {
        pushCheck(
          checks,
          'warn',
          `drafts/${file}`,
          `filename does not match node_id; expected ${expectedFile}.`,
        );
      }

      const duplicate = seenNodeIds.get(frontmatter.node_id);
      if (duplicate) {
        pushCheck(
          checks,
          'error',
          `drafts/${file}`,
          `duplicate node_id "${frontmatter.node_id}" already used by drafts/${duplicate}.`,
        );
      } else {
        seenNodeIds.set(frontmatter.node_id, file);
      }
    } catch (error) {
      const message =
        error instanceof z.ZodError
          ? formatZodError(error)
          : error instanceof Error
            ? error.message
            : String(error);

      pushCheck(checks, 'error', `drafts/${file}`, message);
    }
  }

  pushCheck(
    checks,
    'ok',
    'drafts',
    `Checked ${files.length} draft artifact${files.length === 1 ? '' : 's'}.`,
  );

  return records;
}

async function validateEdges(
  labDir: string,
  nodeIds: ReadonlySet<string>,
  checks: DoctorCheck[],
): Promise<void> {
  const path = resolve(labDir, 'edges.jsonl');

  if (!existsSync(path)) {
    return;
  }

  const content = await readFile(path, 'utf8');
  const lines = content.split('\n');
  const seenEdgeIds = new Set<string>();
  let edgeCount = 0;

  for (const [index, rawLine] of lines.entries()) {
    const line = rawLine.trim();

    if (line.length === 0) {
      continue;
    }

    edgeCount += 1;

    try {
      const parsedJson: unknown = JSON.parse(line);
      const parsedEdge = EdgeSchema.safeParse(parsedJson);

      if (!parsedEdge.success) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          formatZodError(parsedEdge.error),
        );
        continue;
      }

      const edge = parsedEdge.data;

      if (seenEdgeIds.has(edge.edge_id)) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          `duplicate edge_id "${edge.edge_id}".`,
        );
      } else {
        seenEdgeIds.add(edge.edge_id);
      }

      if (!nodeIds.has(edge.from)) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          `from ref "${edge.from}" does not exist in lab/drafts/.`,
        );
      }

      if (!nodeIds.has(edge.to)) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          `to ref "${edge.to}" does not exist in lab/drafts/.`,
        );
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      pushCheck(checks, 'error', `edges.jsonl:${index + 1}`, message);
    }
  }

  pushCheck(
    checks,
    'ok',
    'edges.jsonl',
    `Checked ${edgeCount} edge${edgeCount === 1 ? '' : 's'}.`,
  );
}

async function validateIndex(
  labDir: string,
  checks: DoctorCheck[],
): Promise<void> {
  const path = resolve(labDir, 'index.md');

  if (!existsSync(path)) {
    return;
  }

  const current = await readFile(path, 'utf8');

  if (!current.startsWith(INDEX_AUTOGENERATED_HEADER)) {
    pushCheck(
      checks,
      'warn',
      'index.md',
      'missing auto-generated header; manual edits are not preserved.',
    );
  }

  try {
    const expected = await renderLabIndex(labDir);

    if (
      normalizeGeneratedIndex(current) !== normalizeGeneratedIndex(expected)
    ) {
      pushCheck(
        checks,
        'warn',
        'index.md',
        'generated catalog is stale; run amore doctor --repair.',
      );
      return;
    }

    pushCheck(checks, 'ok', 'index.md', 'Generated catalog is current.');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    pushCheck(
      checks,
      'error',
      'index.md',
      `cannot render generated catalog: ${message}`,
    );
  }
}

function computeExitCode(checks: DoctorCheck[]): 0 | 1 | 2 {
  if (checks.some((check) => check.status === 'error')) {
    return 1;
  }

  if (checks.some((check) => check.status === 'warn')) {
    return 2;
  }

  return 0;
}

export async function runDoctor(
  options: DoctorOptions = {},
): Promise<DoctorResult> {
  const cwd = options.cwd ?? process.cwd();
  const labDir = resolveLabDir(cwd, options.labDir);
  const checks: DoctorCheck[] = [];
  let repaired = false;

  if (options.repair) {
    try {
      await createLab(cwd, {
        labDir: options.labDir,
        reconcile: true,
      });
      await rebuildLabIndex(labDir);
      repaired = true;
      pushCheck(
        checks,
        'ok',
        'repair',
        'Repaired safe layout files and regenerated index.md.',
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      pushCheck(checks, 'error', 'repair', message);
    }
  }

  const layout = await validateLabLayout(cwd, { labDir: options.labDir });
  if (layout.ok) {
    pushCheck(checks, 'ok', 'layout', 'Required lab files are present.');
  } else {
    pushCheck(
      checks,
      'error',
      'layout',
      `Missing required item${layout.missing.length === 1 ? '' : 's'}: ${layout.missing.join(', ')}.`,
    );
  }

  const drafts = await validateDrafts(labDir, checks);
  const nodeIds = new Set(drafts.map((draft) => draft.nodeId));

  await validateEdges(labDir, nodeIds, checks);
  await validateIndex(labDir, checks);

  const exitCode = computeExitCode(checks);

  return {
    ok: exitCode === 0,
    exitCode,
    labDir,
    repaired,
    checks,
  };
}

function statusIcon(status: DoctorStatus): string {
  if (status === 'ok') {
    return 'OK';
  }

  if (status === 'warn') {
    return 'WARN';
  }

  return 'ERROR';
}

export function printDoctorResult(result: DoctorResult, cwd: string): void {
  logger.info(`Lab: ${relative(cwd, result.labDir) || '.'}`);

  for (const check of result.checks) {
    const message = `${statusIcon(check.status)} ${check.label}: ${check.message}`;

    if (check.status === 'error') {
      logger.error(message);
    } else if (check.status === 'warn') {
      logger.warn(message);
    } else {
      logger.info(message);
    }
  }

  if (result.exitCode === 0) {
    logger.success('Doctor passed.');
  } else if (result.exitCode === 2) {
    logger.warn('Doctor found warnings only.');
  } else {
    logger.error('Doctor found errors.');
  }
}

export async function doctor(options: DoctorOptions = {}): Promise<number> {
  const cwd = options.cwd ?? process.cwd();
  const result = await runDoctor(options);

  if (options.json) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    printDoctorResult(result, cwd);
  }

  return result.exitCode;
}
