import { existsSync } from 'node:fs';
import { readFile, readdir } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';
import { z } from 'zod';
import pkg from '../../package.json' with { type: 'json' };
import { loadAmoreConfig } from '../config';
import { DEFAULT_PERSONA_MODELS } from '../config/constants';
import { AmoreConfigSchema } from '../config/schema';
import {
  EdgeSchema,
  createLab,
  parseArtifactMarkdown,
  rebuildLabIndex,
  renderLabIndex,
  resolveLabDir,
  validateLabLayout,
} from '../lab';
import { INDEX_AUTOGENERATED_HEADER } from '../lab/indexer';
import { logger } from '../utils';
import { isAmoreBundledSkillsPath } from './bootstrap';

export interface DoctorOptions {
  cwd?: string;
  labDir?: string;
  json?: boolean;
  repair?: boolean;
}

export type DoctorStatus = 'ok' | 'warn' | 'error';

export interface DoctorCheck {
  status: DoctorStatus;
  label: string;
  message: string;
}

export interface DoctorResult {
  ok: boolean;
  exitCode: 0 | 1 | 2;
  labDir: string;
  repaired: boolean;
  checks: DoctorCheck[];
}

interface DraftRecord {
  file: string;
  nodeId: string;
}

interface SkillFrontmatter {
  name?: unknown;
  description?: unknown;
}

const AMORE_PLUGIN_NAME = 'ah-my-openresearch';
const AMORE_PLUGIN_ENTRY = `${AMORE_PLUGIN_NAME}@${pkg.version}`;
const AMORE_INSTRUCTIONS_FILE = 'AGENTS.md';
const AMORE_DEFAULT_AGENT = 'orchestrator';
const DISABLED_DEFAULT_AGENTS = ['build', 'plan'] as const;
const DOCTOR_FILE = fileURLToPath(import.meta.url);
const BUNDLED_SKILLS_DIR = resolveBundledSkillsDir(DOCTOR_FILE);
const REQUIRED_BUNDLED_SKILLS = [
  'analyze-results',
  'claim-extract',
  'council-session',
  'gap-map',
  'idea-creator',
  'intake-dispatch-summary',
  'monitor-experiment',
  'novelty-vs-wiki',
  'paper-audit',
  'paper-figure',
  'paper-plan',
  'paper-search',
  'research-refine',
  'run-experiment',
  'wiki-ingest',
  'wiki-lint',
] as const;

function resolveBundledSkillsDir(moduleFile: string): string {
  const moduleDir = dirname(moduleFile);
  const candidates = [
    // Source mode: src/cli/doctor.ts -> src/skills.
    resolve(moduleDir, '..', 'skills'),
    // Published bundle: dist/cli/index.js -> src/skills.
    resolve(moduleDir, '..', '..', 'src', 'skills'),
  ];
  return candidates.find((path) => existsSync(path)) ?? candidates[0];
}

function formatZodError(error: z.ZodError): string {
  return error.issues
    .map((issue) => {
      const path = issue.path.length > 0 ? `${issue.path.join('.')}: ` : '';
      return `${path}${issue.message}`;
    })
    .join('; ');
}

function pushCheck(
  checks: DoctorCheck[],
  status: DoctorStatus,
  label: string,
  message: string,
): void {
  checks.push({ status, label, message });
}

function expectedDraftFilename(nodeId: string): string {
  return `${nodeId.replace(':', '-')}.md`;
}

function normalizeGeneratedIndex(content: string): string {
  return content
    .replace(/^Generated: .+$/m, 'Generated: <ignored>')
    .replace(/^- Last validation: .+$/m, '- Last validation: <ignored>');
}

function formatError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function isJsonObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function configContainsEntry(value: unknown, expected: string): boolean {
  if (typeof value === 'string') {
    return value === expected;
  }

  if (!Array.isArray(value)) {
    return false;
  }

  return value.some((entry) => {
    if (typeof entry === 'string') {
      return entry === expected;
    }
    return Array.isArray(entry) && entry[0] === expected;
  });
}

function configContainsExactPlugin(value: unknown, expected: string): boolean {
  if (typeof value === 'string') {
    return value === expected;
  }

  if (!Array.isArray(value)) {
    return false;
  }

  return value.some((entry) => {
    if (typeof entry === 'string') {
      return entry === expected;
    }
    return Array.isArray(entry) && entry[0] === expected;
  });
}

function stringArray(value: unknown): string[] | null {
  if (!Array.isArray(value)) {
    return null;
  }
  return value.every((entry) => typeof entry === 'string') ? value : null;
}

async function validateAmoreConfig(
  labDir: string,
  checks: DoctorCheck[],
): Promise<void> {
  const configPath = resolve(labDir, 'config.json');

  if (!existsSync(configPath)) {
    return;
  }

  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(await readFile(configPath, 'utf8'));
  } catch (error) {
    pushCheck(
      checks,
      'error',
      'lab/config.json',
      `invalid JSON: ${formatError(error)}`,
    );
    return;
  }

  const parsedConfig = AmoreConfigSchema.safeParse(parsedJson);
  if (!parsedConfig.success) {
    pushCheck(
      checks,
      'error',
      'lab/config.json',
      formatZodError(parsedConfig.error),
    );
    return;
  }

  pushCheck(checks, 'ok', 'lab/config.json', 'amore config is valid.');
}

function hasDisabledAgent(
  config: Record<string, unknown>,
  agentName: string,
): boolean {
  if (!isJsonObject(config.agent)) {
    return false;
  }

  const entry = config.agent[agentName];
  return isJsonObject(entry) && entry.disable === true;
}

async function validateRequiredBundledSkills(skillsDir: string): Promise<{
  checked: number;
  failures: string[];
}> {
  const failures: string[] = [];

  if (!existsSync(skillsDir)) {
    return {
      checked: 0,
      failures: [`bundled skills directory does not exist: ${skillsDir}`],
    };
  }

  for (const skillName of REQUIRED_BUNDLED_SKILLS) {
    const skillPath = resolve(skillsDir, skillName, 'SKILL.md');
    if (!existsSync(skillPath)) {
      failures.push(`${skillName}: missing SKILL.md`);
      continue;
    }

    let raw: string;
    try {
      raw = await readFile(skillPath, 'utf8');
    } catch (error) {
      failures.push(
        `${skillName}: could not read SKILL.md: ${formatError(error)}`,
      );
      continue;
    }

    const frontmatter = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!frontmatter) {
      failures.push(`${skillName}: missing YAML frontmatter`);
      continue;
    }

    let parsed: SkillFrontmatter;
    try {
      parsed = YAML.parse(frontmatter[1]) as SkillFrontmatter;
    } catch (error) {
      failures.push(
        `${skillName}: invalid YAML frontmatter: ${formatError(error)}`,
      );
      continue;
    }

    if (parsed.name !== skillName) {
      failures.push(`${skillName}: frontmatter name must match directory`);
    }
    if (
      typeof parsed.description !== 'string' ||
      parsed.description.trim().length === 0
    ) {
      failures.push(`${skillName}: description must be a non-empty string`);
    }
  }

  return { checked: REQUIRED_BUNDLED_SKILLS.length, failures };
}

async function validateOpenCodeWiring(
  cwd: string,
  checks: DoctorCheck[],
): Promise<void> {
  const opencodePath = resolve(cwd, 'opencode.json');

  if (!existsSync(opencodePath)) {
    pushCheck(
      checks,
      'error',
      'opencode.json',
      'missing; run amore install so OpenCode can load the plugin, project AGENTS.md, disabled defaults, and bundled skills.',
    );
    return;
  }

  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(await readFile(opencodePath, 'utf8'));
  } catch (error) {
    pushCheck(
      checks,
      'error',
      'opencode.json',
      `invalid JSON: ${formatError(error)}`,
    );
    return;
  }

  if (!isJsonObject(parsedJson)) {
    pushCheck(checks, 'error', 'opencode.json', 'must be a JSON object.');
    return;
  }

  const config = parsedJson;
  const configFailures: string[] = [];

  if (!configContainsExactPlugin(config.plugin, AMORE_PLUGIN_ENTRY)) {
    configFailures.push(`plugin is missing "${AMORE_PLUGIN_ENTRY}"`);
  }
  if (!configContainsEntry(config.instructions, AMORE_INSTRUCTIONS_FILE)) {
    configFailures.push(`instructions is missing "${AMORE_INSTRUCTIONS_FILE}"`);
  } else if (!existsSync(resolve(cwd, AMORE_INSTRUCTIONS_FILE))) {
    configFailures.push(`${AMORE_INSTRUCTIONS_FILE} is referenced but missing`);
  }
  if (config.default_agent !== AMORE_DEFAULT_AGENT) {
    configFailures.push(`default_agent is not "${AMORE_DEFAULT_AGENT}"`);
  }

  if (configFailures.length > 0) {
    pushCheck(checks, 'error', 'opencode.json', configFailures.join('; '));
  } else {
    pushCheck(
      checks,
      'ok',
      'opencode.json',
      'Plugin, AGENTS.md, and default_agent are wired.',
    );
  }

  const agentFailures = DISABLED_DEFAULT_AGENTS.filter(
    (agentName) => !hasDisabledAgent(config, agentName),
  ).map((agentName) => `agent.${agentName}.disable is not true`);

  if (agentFailures.length > 0) {
    pushCheck(checks, 'error', 'opencode agents', agentFailures.join('; '));
  } else {
    pushCheck(
      checks,
      'ok',
      'opencode agents',
      'OpenCode build/plan defaults are disabled.',
    );
  }

  // The plugin's config hook injects the bundled skills path at runtime;
  // opencode.json is not required (or expected) to list it. Error only when
  // the bundled skills themselves are broken; warn about machine-local
  // entries older installers wrote.
  const skillValidation =
    await validateRequiredBundledSkills(BUNDLED_SKILLS_DIR);

  if (skillValidation.failures.length > 0) {
    pushCheck(
      checks,
      'error',
      'opencode skills',
      skillValidation.failures.join('; '),
    );
  } else {
    pushCheck(
      checks,
      'ok',
      'opencode skills',
      `Checked ${skillValidation.checked} bundled skills; the plugin injects their path at runtime.`,
    );
  }

  const skills = isJsonObject(config.skills) ? config.skills : null;
  const paths = skills ? stringArray(skills.paths) : null;
  const staleSkillsPaths = (paths ?? []).filter(isAmoreBundledSkillsPath);
  if (staleSkillsPaths.length > 0) {
    pushCheck(
      checks,
      'warn',
      'opencode skills.paths',
      `skills.paths contains machine-local amore entries (${staleSkillsPaths.join(', ')}); re-run amore install to remove them.`,
    );
  }
}

/**
 * Informational check: which providers the resolved persona models require.
 * Always `ok` — whether a provider is actually configured cannot be checked
 * reliably (OpenCode auth store, env vars, proxy providers), so this only
 * surfaces the dependency instead of guessing.
 */
function checkPersonaModelProviders(cwd: string, checks: DoctorCheck[]): void {
  const models: Record<string, string> = { ...DEFAULT_PERSONA_MODELS };
  const personas = loadAmoreConfig(cwd)?.personas;
  if (personas) {
    for (const [name, persona] of Object.entries(personas)) {
      if (persona?.model) {
        models[name] = persona.model;
      }
    }
  }
  const providers = [
    ...new Set(
      Object.values(models).map((model) => model.split('/')[0] ?? model),
    ),
  ].sort();
  pushCheck(
    checks,
    'ok',
    'persona models',
    `Personas resolve to provider${providers.length === 1 ? '' : 's'}: ${providers.join(', ')}. Make sure ${providers.length === 1 ? 'it is' : 'they are'} configured in OpenCode, or switch via amore install --models / personas.<name>.model.`,
  );
}

async function validateDrafts(
  labDir: string,
  checks: DoctorCheck[],
): Promise<DraftRecord[]> {
  const draftsDir = resolve(labDir, 'drafts');

  if (!existsSync(draftsDir)) {
    return [];
  }

  const files = (await readdir(draftsDir)).filter((file) =>
    file.endsWith('.md'),
  );
  const records: DraftRecord[] = [];
  const seenNodeIds = new Map<string, string>();

  if (files.length === 0) {
    pushCheck(checks, 'ok', 'drafts', 'No draft artifacts yet.');
    return records;
  }

  for (const file of files.sort()) {
    const path = resolve(draftsDir, file);

    try {
      const markdown = await readFile(path, 'utf8');
      const { frontmatter } = parseArtifactMarkdown(markdown);
      const expectedFile = expectedDraftFilename(frontmatter.node_id);

      records.push({ file, nodeId: frontmatter.node_id });

      if (frontmatter.type !== frontmatter.node_id.split(':', 1)[0]) {
        pushCheck(
          checks,
          'error',
          `drafts/${file}`,
          `type "${frontmatter.type}" does not match node_id "${frontmatter.node_id}".`,
        );
      }

      if (file !== expectedFile) {
        pushCheck(
          checks,
          'warn',
          `drafts/${file}`,
          `filename does not match node_id; expected ${expectedFile}.`,
        );
      }

      const duplicate = seenNodeIds.get(frontmatter.node_id);
      if (duplicate) {
        pushCheck(
          checks,
          'error',
          `drafts/${file}`,
          `duplicate node_id "${frontmatter.node_id}" already used by drafts/${duplicate}.`,
        );
      } else {
        seenNodeIds.set(frontmatter.node_id, file);
      }
    } catch (error) {
      const message =
        error instanceof z.ZodError
          ? formatZodError(error)
          : error instanceof Error
            ? error.message
            : String(error);

      pushCheck(checks, 'error', `drafts/${file}`, message);
    }
  }

  pushCheck(
    checks,
    'ok',
    'drafts',
    `Checked ${files.length} draft artifact${files.length === 1 ? '' : 's'}.`,
  );

  return records;
}

async function validateEdges(
  labDir: string,
  nodeIds: ReadonlySet<string>,
  checks: DoctorCheck[],
): Promise<void> {
  const path = resolve(labDir, 'edges.jsonl');

  if (!existsSync(path)) {
    return;
  }

  const content = await readFile(path, 'utf8');
  const lines = content.split('\n');
  const seenEdgeIds = new Set<string>();
  let edgeCount = 0;

  for (const [index, rawLine] of lines.entries()) {
    const line = rawLine.trim();

    if (line.length === 0) {
      continue;
    }

    edgeCount += 1;

    try {
      const parsedJson: unknown = JSON.parse(line);
      const parsedEdge = EdgeSchema.safeParse(parsedJson);

      if (!parsedEdge.success) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          formatZodError(parsedEdge.error),
        );
        continue;
      }

      const edge = parsedEdge.data;

      if (seenEdgeIds.has(edge.edge_id)) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          `duplicate edge_id "${edge.edge_id}".`,
        );
      } else {
        seenEdgeIds.add(edge.edge_id);
      }

      if (!nodeIds.has(edge.from)) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          `from ref "${edge.from}" does not exist in lab/drafts/.`,
        );
      }

      if (!nodeIds.has(edge.to)) {
        pushCheck(
          checks,
          'error',
          `edges.jsonl:${index + 1}`,
          `to ref "${edge.to}" does not exist in lab/drafts/.`,
        );
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      pushCheck(checks, 'error', `edges.jsonl:${index + 1}`, message);
    }
  }

  pushCheck(
    checks,
    'ok',
    'edges.jsonl',
    `Checked ${edgeCount} edge${edgeCount === 1 ? '' : 's'}.`,
  );
}

async function validateIndex(
  labDir: string,
  checks: DoctorCheck[],
): Promise<void> {
  const path = resolve(labDir, 'index.md');

  if (!existsSync(path)) {
    return;
  }

  const current = await readFile(path, 'utf8');

  if (!current.startsWith(INDEX_AUTOGENERATED_HEADER)) {
    pushCheck(
      checks,
      'warn',
      'index.md',
      'missing auto-generated header; manual edits are not preserved.',
    );
  }

  try {
    const expected = await renderLabIndex(labDir);

    if (
      normalizeGeneratedIndex(current) !== normalizeGeneratedIndex(expected)
    ) {
      pushCheck(
        checks,
        'warn',
        'index.md',
        'generated catalog is stale; run amore doctor --repair.',
      );
      return;
    }

    pushCheck(checks, 'ok', 'index.md', 'Generated catalog is current.');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    pushCheck(
      checks,
      'error',
      'index.md',
      `cannot render generated catalog: ${message}`,
    );
  }
}

function computeExitCode(checks: DoctorCheck[]): 0 | 1 | 2 {
  if (checks.some((check) => check.status === 'error')) {
    return 1;
  }

  if (checks.some((check) => check.status === 'warn')) {
    return 2;
  }

  return 0;
}

export async function runDoctor(
  options: DoctorOptions = {},
): Promise<DoctorResult> {
  const cwd = options.cwd ?? process.cwd();
  const labDir = resolveLabDir(cwd, options.labDir);
  const checks: DoctorCheck[] = [];
  let repaired = false;

  if (options.repair) {
    try {
      await createLab(cwd, {
        labDir: options.labDir,
        reconcile: true,
      });
      await rebuildLabIndex(labDir);
      repaired = true;
      pushCheck(
        checks,
        'ok',
        'repair',
        'Repaired safe layout files and regenerated index.md.',
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      pushCheck(checks, 'error', 'repair', message);
    }
  }

  const layout = await validateLabLayout(cwd, { labDir: options.labDir });
  if (layout.ok) {
    pushCheck(checks, 'ok', 'layout', 'Required lab files are present.');
  } else {
    pushCheck(
      checks,
      'error',
      'layout',
      `Missing required item${layout.missing.length === 1 ? '' : 's'}: ${layout.missing.join(', ')}.`,
    );
  }

  await validateAmoreConfig(labDir, checks);

  await validateOpenCodeWiring(cwd, checks);
  checkPersonaModelProviders(cwd, checks);

  const drafts = await validateDrafts(labDir, checks);
  const nodeIds = new Set(drafts.map((draft) => draft.nodeId));

  await validateEdges(labDir, nodeIds, checks);
  await validateIndex(labDir, checks);

  const exitCode = computeExitCode(checks);

  return {
    ok: exitCode === 0,
    exitCode,
    labDir,
    repaired,
    checks,
  };
}

function statusIcon(status: DoctorStatus): string {
  if (status === 'ok') {
    return 'OK';
  }

  if (status === 'warn') {
    return 'WARN';
  }

  return 'ERROR';
}

export function printDoctorResult(result: DoctorResult, cwd: string): void {
  logger.info(`Lab: ${relative(cwd, result.labDir) || '.'}`);

  for (const check of result.checks) {
    const message = `${statusIcon(check.status)} ${check.label}: ${check.message}`;

    if (check.status === 'error') {
      logger.error(message);
    } else if (check.status === 'warn') {
      logger.warn(message);
    } else {
      logger.info(message);
    }
  }

  if (result.exitCode === 0) {
    logger.success('Doctor passed.');
  } else if (result.exitCode === 2) {
    logger.warn('Doctor found warnings only.');
  } else {
    logger.error('Doctor found errors.');
  }
}

export async function doctor(options: DoctorOptions = {}): Promise<number> {
  const cwd = options.cwd ?? process.cwd();
  const result = await runDoctor(options);

  if (options.json) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    printDoctorResult(result, cwd);
  }

  return result.exitCode;
}
