import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, extname, resolve } from 'node:path';
import {
  type ArtifactFrontmatter,
  parseArtifactMarkdown,
} from './artifact-schema';
import { countBrokenEdgeRefs, readEdges } from './edges';
import { formatLabTimestamp } from './log';

export const INDEX_AUTOGENERATED_HEADER =
  '<!-- AUTO-GENERATED by amore. Do not edit by hand. -->';

interface IndexedArtifact {
  file: string;
  link: string;
  frontmatter: ArtifactFrontmatter;
}

type ClaimArtifact = IndexedArtifact & {
  frontmatter: Extract<ArtifactFrontmatter, { type: 'claim' }>;
};

type ExperimentArtifact = IndexedArtifact & {
  frontmatter: Extract<ArtifactFrontmatter, { type: 'exp' }>;
};

type IdeaArtifact = IndexedArtifact & {
  frontmatter: Extract<ArtifactFrontmatter, { type: 'idea' }>;
};

function isClaimArtifact(artifact: IndexedArtifact): artifact is ClaimArtifact {
  return artifact.frontmatter.type === 'claim';
}

function isExperimentArtifact(
  artifact: IndexedArtifact,
): artifact is ExperimentArtifact {
  return artifact.frontmatter.type === 'exp';
}

function isIdeaArtifact(artifact: IndexedArtifact): artifact is IdeaArtifact {
  return artifact.frontmatter.type === 'idea';
}

function wikilinkForDraft(file: string): string {
  return `[[drafts/${file.slice(0, -extname(file).length)}]]`;
}

async function readDraftArtifacts(labDir: string): Promise<IndexedArtifact[]> {
  const draftsDir = resolve(labDir, 'drafts');
  const files = (await readdir(draftsDir)).filter((file) =>
    file.endsWith('.md'),
  );
  const artifacts: IndexedArtifact[] = [];

  for (const file of files) {
    const markdown = await readFile(resolve(draftsDir, file), 'utf8');
    const { frontmatter } = parseArtifactMarkdown(markdown);
    artifacts.push({
      file,
      link: wikilinkForDraft(file),
      frontmatter,
    });
  }

  return artifacts.sort((left, right) => left.file.localeCompare(right.file));
}

function tableOrEmpty(headers: string[], rows: string[][]): string {
  if (rows.length === 0) {
    return '_None yet._\n';
  }

  const header = `| ${headers.join(' | ')} |`;
  const divider = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => `| ${row.join(' | ')} |`);
  return `${[header, divider, ...body].join('\n')}\n`;
}

function renderClaims(artifacts: IndexedArtifact[]): string {
  const rows = artifacts
    .filter(isClaimArtifact)
    .map((artifact) => [
      artifact.link,
      artifact.frontmatter.status,
      artifact.frontmatter.confidence,
      artifact.frontmatter.title,
      artifact.frontmatter.updated,
    ]);

  return tableOrEmpty(['ID', 'Status', 'Confidence', 'Title', 'Updated'], rows);
}

function renderExperiments(artifacts: IndexedArtifact[]): string {
  const rows = artifacts
    .filter(isExperimentArtifact)
    .map((artifact) => [
      artifact.link,
      artifact.frontmatter.status,
      artifact.frontmatter.results.outcome,
      artifact.frontmatter.title,
      artifact.frontmatter.updated,
    ]);

  return tableOrEmpty(['ID', 'Status', 'Outcome', 'Title', 'Updated'], rows);
}

function renderIdeas(artifacts: IndexedArtifact[]): string {
  const rows = artifacts
    .filter(isIdeaArtifact)
    .map((artifact) => [
      artifact.link,
      artifact.frontmatter.status,
      artifact.frontmatter.title,
      artifact.frontmatter.updated,
    ]);

  return tableOrEmpty(['ID', 'Status', 'Title', 'Updated'], rows);
}

export async function renderLabIndex(labDir: string): Promise<string> {
  const artifacts = await readDraftArtifacts(labDir);
  const nodeIds = new Set(
    artifacts.map((artifact) => artifact.frontmatter.node_id),
  );
  const edges = await readEdges(labDir);
  const brokenRefs = countBrokenEdgeRefs(edges, nodeIds);
  const generated = formatLabTimestamp();

  return `${INDEX_AUTOGENERATED_HEADER}
# Lab Index

Generated: ${generated}

## Claims

${renderClaims(artifacts)}

## Experiments

${renderExperiments(artifacts)}

## Ideas

${renderIdeas(artifacts)}

## Graph Health

- Nodes: ${nodeIds.size}
- Edges: ${edges.length}
- Broken refs: ${brokenRefs}
- Last validation: ${generated}
`;
}

export async function rebuildLabIndex(labDir: string): Promise<void> {
  await writeFile(
    resolve(labDir, 'index.md'),
    await renderLabIndex(labDir),
    'utf8',
  );
}

export function getDraftArtifactName(filePath: string): string {
  return basename(filePath, extname(filePath));
}
